name: Run Unit Tests

on: [push] # when a user make a git push i will exec:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # download the code inside our machine

      - uses: actions/setup-node@v3 # setup node
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci # install dependencies

      - run: npm run test